export default {
  "interpolateBlues": "Blue",
  "interpolateGreens": "Green",
  "interpolateGreys": "Grey",
  "interpolateOranges": "Orange",
  "interpolatePurples": "Purple",
  "interpolateReds": "Red",

  "interpolateBrBG": "Brown Blue-Green",
  "interpolateBuGn": "Blue Green",
  "interpolateBuPu": "Blue Purple",
  "interpolateGnBu": "Green Blue",
  "interpolateOrRd": "Orange Red",
  "interpolatePiYG": "Pink Green",
  "interpolatePRGn": "Purple Green",
  "interpolatePuBu": "Purple Blue",
  "interpolatePuBuGn": "Purple Blue Green",
  "interpolatePuOr": "Purple Orange",
  "interpolatePuRd": "Purple Red",
  "interpolateRdBu": "Red Blue",
  "interpolateRdGy": "Red Grey",
  "interpolateRdPu": "Red Purple",
  "interpolateRdYlBu": "Red Yellow to Blue",
  "interpolateRdYlGn": "Red Yellow to Green",
  "interpolateYlGn": "Yellow Green",
  "interpolateYlGnBu": "Yellow Green Blue",
  "interpolateYlOrBr": "Yellow Orange Brown",
  "interpolateYlOrRd": "Yellow Orange Red",

  "interpolateCool": "Cool",
  "interpolateInferno": "Inferno",
  "interpolateMagma": "Magma",
  "interpolatePlasma": "Plasma",
  "interpolateSpectral": "Spectral",
  "interpolateViridis": "Viridis",
  "interpolateWarm": "Warm"
};
